import numpy as pd
import pandas as pd
import numpy as np
from scipy.stats import entropy
import logging

logger = logging.getLogger(__name__)

class FeatureEngineer:
    """
    Computes features from raw pricing data for the regime detection model.
    """
    def __init__(self, data: pd.DataFrame):
        """
        Args:
            data (pd.DataFrame): Raw price DataFrame where index is Datetime and columns are asset prices.
        """
        self.data = data
        self.features = pd.DataFrame(index=self.data.index)
        
    def add_log_returns(self):
        """Calculate logarithmic returns."""
        for col in self.data.columns:
            self.features[f'{col}_log_return'] = np.log(self.data[col] / self.data[col].shift(1))
        logger.info("Log returns calculated.")
        return self

    def add_realized_volatility(self, window=21):
        """Calculate rolling realized volatility (annualized)."""
        for col in self.data.columns:
            log_ret_col = f'{col}_log_return'
            if log_ret_col not in self.features.columns:
                self.add_log_returns()
            
            # Annualized volatility (assuming 252 trading days)
            self.features[f'{col}_volatility_{window}d'] = (
                self.features[log_ret_col].rolling(window=window).std() * np.sqrt(252)
            )
        logger.info(f"{window}-day rolling volatility calculated.")
        return self
        
    def add_cross_asset_correlation(self, window=63):
        """Calculate rolling cross-asset correlation if multiple assets exist."""
        if len(self.data.columns) > 1:
            assets = list(self.data.columns)
            # Create a dictionary to store correlations
            correlations = {}
            for i in range(len(assets)):
                for j in range(i + 1, len(assets)):
                    asset1, asset2 = assets[i], assets[j]
                    ret1 = self.features[f'{asset1}_log_return']
                    ret2 = self.features[f'{asset2}_log_return']
                    corr_name = f'corr_{asset1}_{asset2}_{window}d'
                    correlations[corr_name] = ret1.rolling(window=window).corr(ret2)
                    
            corr_df = pd.DataFrame(correlations)
            self.features = pd.concat([self.features, corr_df], axis=1)
            logger.info("Cross-asset correlations calculated.")
        else:
            logger.info("Only one asset provided; skipping cross-asset correlation.")
        return self

    def add_cusum(self, target_col, threshold=0.05, drift=0.0):
        """
        CUSUM structural break detection filter.
        Adapted to be a continuous feature representing the cumulative sum.
        """
        if target_col not in self.features.columns:
            raise ValueError(f"{target_col} not in features.")
            
        series = self.features[target_col].fillna(0).values
        pos_cusum = np.zeros_like(series)
        neg_cusum = np.zeros_like(series)
        
        for i in range(1, len(series)):
            s = series[i]
            pos_cusum[i] = max(0, pos_cusum[i-1] + s - drift)
            neg_cusum[i] = min(0, neg_cusum[i-1] + s + drift)
            
        self.features[f'{target_col}_pos_cusum'] = pos_cusum
        self.features[f'{target_col}_neg_cusum'] = neg_cusum
        logger.info(f"CUSUM features calculated for {target_col}.")
        return self
        
    def add_rolling_entropy(self, target_col, window=63, bins=10):
        """
        Calculate Shannon entropy over a rolling window based on a histogram of returns.
        """
        if target_col not in self.features.columns:
            raise ValueError(f"{target_col} not in features.")
            
        def calc_entropy(x):
            counts, _ = np.histogram(x, bins=bins)
            return entropy(counts)
            
        self.features[f'{target_col}_entropy_{window}d'] = (
            self.features[target_col].rolling(window=window).apply(calc_entropy, raw=True)
        )
        logger.info(f"Rolling Shannon entropy calculated for {target_col}.")
        return self

    def generate_features(self) -> pd.DataFrame:
        """Run the full feature engineering pipeline."""
        self.add_log_returns()
        self.add_realized_volatility(window=21)
        self.add_cross_asset_correlation(window=63)
        
        # Add CUSUM and Entropy for the first asset's log return as a baseline
        first_asset_ret = f"{self.data.columns[0]}_log_return"
        self.add_cusum(first_asset_ret)
        self.add_rolling_entropy(first_asset_ret, window=63)
        
        # Drop NaN values generated by rolling windows
        self.features.dropna(inplace=True)
        return self.features

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    # Dummy data test
    dates = pd.date_range("2020-01-01", periods=100)
    df = pd.DataFrame({"^GSPC": np.random.randn(100).cumsum() + 100}, index=dates)
    engineer = FeatureEngineer(df)
    features = engineer.generate_features()
    print(features.head())
